on:
  push:

jobs:
  test:
    runs-on: [self-hosted, data-platform, ubuntu, ARM64, 4cpu16ram]
    steps:
      - shell: python
        run: |
          import platform
          print(platform.machine())
